version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  app:
    build: .
    restart: on-failure
    expose:
      - 3000
    depends_on:
      - postgres-db
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=8ded9e0fc3767933d68442770258812e
      - PG_HOST=postgres-db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - REDIS_HOST=redis
    volumes:
      # - /app/node_modules
      - .:/app
  postgres-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reddit_api_clone
    expose:
      - 5432
  redis:
    image: redis
    restart: always
    expose:
      - 6379
